[package]
name = "wtfisjet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
num-rational = { version = "0.4.0", optional = true }

[features]
default = ["num-rational"]
